### ISSUE TITLE
m216_defconfig missing

### ISSUE THREAD

**Issue by Anubhaav** [LG-K10/android_kernel_lge_msm8916#1]
A default configuration file for m216 (**m216_defconfig**) is missing for the **lineage-15.1** branch.

**Comment by dom133** [comment]
https://github.com/LG-K10/android_kernel_lge_msm8916/blob/lineage-15.1-WIP/arch/arm/configs/m216_defconfig

**Comment by PVineeth** [comment]
We are trying to fix the kernel for OREO. It will be released soon,

**Comment by Anubhaav** [comment]
I was trying to build RR-OS 6.0.0 & LOS 15.1 using the **lineage-15.1** branch, & it gave me many warnings & errors. Will it work if I use the **lineage-15.1-WIP** branch? Anyways, thanks to you all who are contributing their valuable time to fix all these things and make OREO a reality for LG K10! @PVineeth @dom133

**Comment by PVineeth** [comment]
No it will not work with any branch now. We will fix it and inform you soon. @Anubhaav

**Comment by Anubhaav** [comment]
Is there any way I can contribute? @PVineeth

**Comment by PVineeth** [comment]
Will tell you if we need anything. @Anubhaav

**Comment by PVineeth** [comment]
I fixed the kernel @Anubhaav . You can work on the trees if you want to.

**Comment by Anubhaav** [comment]
I'll definitely start working & let you know if any problems are there. And thanks a lot for contributing!
